# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/npm.gitlab-ci.yml
stages:
  - build
  - test
  - deploy

# 构建阶段
build:
  image: node:18
  stage: build
  tags:
    - frontend
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - sudo cp -r ./dist /usr/share/nginx


#测试阶段
test:
  image: node:18
  stage: test
  dependencies: [build] # 依赖于构建阶段的输出
  tags:
    - frontend
  script:
    - npm run test

deploy:
  stage: deploy
  image: node:18
  tags:
    - frontend
  script:
    - sudo nginx -s reload
#    - sudo docker build  -t app/spy-frontend:latest  .
#    - if [ $(sudo docker ps -aq --filter name=spy-frontend) ];then sudo docker rm -f spy-frontend;fi
#    - sudo docker run -d -p 5173:5173 --rm  --name spy-frontend app/spy-frontend
#    - ./deploy.sh