spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://111.229.131.214:11301/news
      username: root
      password: Spy?1130ywydzz

  jackson:
    time-zone: GMT+8

  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 200MB

  elasticsearch:
    uris: 111.229.131.214:9200
    username:
    password:

  neo4j:
    uri: bolt://123.60.77.90:7687
    authentication:
      username: neo4j
      password: neo4jspy

  rabbitmq:
    host: 123.60.77.90
    port: 5672
    username: admin
    password: adminspy
    virtual-host: /

  flink:
    job-manager-host: 123.60.77.90
    job-manager-port: 8081

  security:
    basic:
      enabled: false

  redis:
    host: 123.60.77.90
    port: 6379
    password: redisspy
    database: 0
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
        max-wait: 100 #连接等待时间

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 3600
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

xfxh:
  # 服务引擎使用 讯飞星火认知大模型V2.0，如果使用 V1.5 需要将 hostUrl 修改为 https://spark-api.xf-yun.com/v1.1/chat
  hostUrl: https://spark-api.xf-yun.com/v3.1/chat
  # 发送请求时指定的访问领域，如果是 V1.5版本 设置为 general，如果是 V2版本 设置为 generalv2
  domain: generalv3
  # 核采样阈值。用于决定结果随机性，取值越高随机性越强即相同的问题得到的不同答案的可能性越高。取值 [0,1]
  temperature: 0.5
  # 模型回答的tokens的最大长度，V1.5取值为[1,4096]，V2.0取值为[1,8192]。
  maxTokens: 8192
  # 大模型回复问题的最大响应时长，单位 s
  maxResponseTime: 120
  # 允许同时连接大模型的 websocket 数，如果是普通（免费）用户为 2，超过这个数连接响应会报错，具体参考官网。
  QPS: 2
  # 用于权限验证，从服务接口认证信息中获取
  appId:
    - 45227df4
    - cbbf0d83
    - bb638503
    - b9279748
  # 用于权限验证，从服务接口认证信息中获取
  apiKey:
    - 0e354f1c70aba5f6c83ff66cc12d6406
    - e9e03bf5c3ecc16bdb87156ee30510e0
    - 548fec35d3e05752b5e20d32e8a771c8
    - d1d60d81529af2084271f09984bad3e5
  # 用于权限验证，从服务接口认证信息中获取
  apiSecret:
    - NzcxMjcxZTIwNDc3M2QwMzk5OTg4Mzcz
    - OGQwNDNmYzMyZGU2ZTdiOTljMmFjNDM4
    - YTcyNGM2Njk2ZWI3YTdhNTQ4NjIzNjk3
    - YWIxMjk3NTczMTEyYmM0N2IxZDk4MmI0



enable-init-data: false
enable-init-esData: false

server:
  port: 9010


redis-constants:
  provinceCountTTL: 2
  promptTTL: 2
